### ISSUE TITLE
Wallet Login & Onboarding

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-agent#353]
- [ ] login
  - [ ] extend http-server to perform OIDC auth code flow with hub-auth
    - [x] backend: configuration
    - [ ] frontend: UI with Login button
    - [x] backend: OIDC login endpoint #357 
    - [x] backend: handle OIDC callback #375 
    - [ ] backend: encrypted storage of access_token #380 
    - [ ] backend: create primary key at key server
    - [ ] backend: split key and create 1 data vault per key share (use access_token) (`controller` == primary key) (spec says: MUST be URI; use did:key)
    - [ ] backend: write key share doc to each SDS and set key server's key as recipient (authZ with `controller` key)
    - [ ] backend: purge primary key from memory
    - [x] backend: session cookie #379 
    - [ ] user identifier cookie #419 
    - [ ] backend: redirect to front end
    - [ ] frontend: init remote KMS with SDS locations of primary key shares
    - [ ] BDD Tests
      - [x] login #385 
      - [ ] docs: #404 
  - [ ] clear all data when user logs out #376
- [ ] wallet lock/unlock:
  - [ ] frontend: at end of onboarding flow: option to register device to unlock the wallet #391
  - [x] parse WebAuthN response (especially the CBOR encoding of the authenticator's public key) [edge-core 78](https://github.com/trustbloc/edge-core/issues/78)
  - [ ] backend: endpoint to fetch WebAuthN PublicKeyCreationOptions #392
  - [x] frontend: do webauthn request and send response to backend #393
  - [ ] backend: verify webauthn response #394
  - [ ] backend: query hub-auth (`/device`) to see if device is compliant with policy #395
- [x] healthcheck #362 
- [ ] support multiple storage implementations #363
- [x] only create new user if no existing user for the same OIDC `sub` is found #381
- [ ] set max age on session cookies #388
- [x] rename http-server component #397
