### ISSUE TITLE
WebAuthn Flow task breakdown 

### ISSUE THREAD

**Issue by talwinder50** [trustbloc/edge-agent#386]
Along with #353, we need to implement lock/unlock capabilities for the web wallet.

- [x] backend:
  - [x] endpoint to fetch WebAuthN PublicKeyCreationOptions #392
  - [x] endpoint to receive and verify webauthn response #394
  - [ ] query hub-auth (`/device`) to see if device is compliant with policy #395
- [x] frontend:
  - [x] at end of onboarding flow: option to register device to unlock the wallet #391
